# XDG: https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"

# Zsh: https://zsh.sourceforge.io/Doc/Release/Files.html#Startup_002fShutdown-Files
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Editor
export EDITOR="nvim"
export VISUAL="nvim"
