# XDG: https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"

# Zsh: https://zsh.sourceforge.io/Doc/Release/Files.html#Startup_002fShutdown-Files
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# Zsh's builtin path array variable to set up PATH.
path=( \
	"$HOME/.local/bin" \
	"$HOME/depot_tools" \
	"$HOME/homebrew/bin" \
	"$HOME/fuchsia/.jiri_root/bin" \
	$path \
)
export PATH

source "$HOME/fuchsia/scripts/fx-env.sh"
source "$HOME/.cargo/env"
